### ISSUE TITLE
Setup codecov GitHub integration

### ISSUE THREAD

**Issue by blueyed** [pypy/pyrepl#44]
While reporting to https://app.codecov.io/gh/pypy/pyrepl/ work in general, there is no commit/PR status being reported.

For this the app needs to be added to the repository.
Docs: https://docs.codecov.io/docs/quick-start ("GitHub App integration").

I've requested access through https://github.com/apps/codecov/installations/new/permissions?target_id=318667 now, but am not sure who receives / might handle it.

**Comment by antocuni** [comment]
I think it's already installed? If I go to `Settings ==> Integrations` I see the following:
![image](https://user-images.githubusercontent.com/344507/120106213-822be980-c15c-11eb-8747-d95c17ef8ece.png)

**Comment by blueyed** [comment]
Yeah, I think @mattip might have done it (https://github.com/pypy/pyrepl/pull/41#issuecomment-850999242).

Thanks everybody.
